accessing
exception
	"Relation named: #exception type: #PythonException opposite: #raise"

	<generated>
	^ exception